### ISSUE TITLE
Session Destroy

### ISSUE THREAD

**Issue by Khurshid11** [wader/gormstore#2]
How can I destroy  session when users logged out including from database which was saved while logged in?

Please, I need it in urgent

**Comment by wader** [comment]
Hi, try to set `MaxAge` to something negative and then save. See https://github.com/wader/gormstore/blob/master/gormstore_test.go#L179

**Comment by wader** [comment]
But i've usually implemented logout by deleting keys from the session and then save. Then the session will still be around but in a "logged out" state.

**Comment by wader** [comment]
@Khurshid11 close?
