### ISSUE TITLE
Session is not reused when request address changed

### ISSUE THREAD

**Issue by Benzhaomin** [wader/gormstore#37]
A `gormSession` object is stored inside the gorilla request context in `Store.New()` and retrieved in `Store.Save()`. Indexing is done using a pointer to the request object. 

In our case, the request pointer can be different between the call to `New()` and the one to `Save()`. We thus fail to retrieve the session and create a new one which then breaks our OAuth flow.

A basic fix is to get the session from DB both in `New()` and `Save()` instead of passing it using the request context. PR incoming.

**Comment by wader** [comment]
Thanks! trying to understand if this could break something for someone... and if there was a reason i used context for this :) as `contextKey` is not exported i can see that would be possible?

**Comment by wader** [comment]
Yeah guess so, had a look at some other stores and some use no context, some std lib context and some gorilla context.

**Comment by wader** [comment]
Closed by #38
