### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by DemonTPx** [wader/gormstore#44]
Hi,

Would it be possible to tag a new version of this package?

I'm using the github.com/gin-contrib/sessions package, which depends on this package (v2.0.0), which in turn depends on github.com/mattn/go-sqlite3 v2.0.3. The whole v2 version branch of that go-sqlite3 package was a mistake by the maintainer and they continued to release packages as v1.* versions.

You've already fixed this in your master branch, but did not yet tag a new version, which would likely fix my problem.

For now I downgraded to a lower version of github.com/gin-contrib/sessions, which doesn't depend on this package, which allows me to use the latest go-sqlite3 package.

Thanks,
Bert

**Comment by wader** [comment]
Hey, sure no problem, good you reminded me. Have tagged master with v2.0.1 now.

**Comment by wader** [comment]
I choosed to bump minor version, i hope that is appropriate if only dependencies have changed

**Comment by DemonTPx** [comment]
Thanks! :)

**Comment by wader** [comment]
👍 haven used v2 sub directory and v2 tags before so let me know if something seems strange
