### ISSUE TITLE
Alternative to cookie?

### ISSUE THREAD

**Issue by Fyb3roptik** [wader/gormstore#53]
Is there a way to send the token via JSON body? Using cookies won't work well for my situation.

**Comment by wader** [comment]
Hey, sorry for late replying. Stranegly i have a vague memory of answering something similar to this before but can't find it :)

Do you have any ideas how an API supporting something like that could look like? guess it would require reading the body but then have to make the body available again for the service code?

**Comment by Fyb3roptik** [comment]
I ended up switching to JWT. No idea how to make this work without cookies and without using oauth other than using JWT

**Comment by wader** [comment]
Ok, had a quick look at some middleware for JWT and they seems get the token from the Authorization header, that i guess would be easier. To somehow extract from the HTTP body feels a bit tricker.

**Comment by Fyb3roptik** [comment]
Yeah it should def be a header. Cookie support for this stuff is dying

**Comment by wader** [comment]
Ok to close?
